import { existsSync } from "node:fs";
import { readFile } from "node:fs/promises";
import { join } from "node:path";
import type { AgentAdapterId, LegacyFileInfo } from "../../types/index.js";
import { METADATA_MARKER, parseMetadataFromContent } from "./metadata.js";

interface LegacyPathDef {
  /** The old path pattern. Use {projectName} placeholder. */
  oldPath: string;
  /** The adapter id that created this file. */
  oldAgent: AgentAdapterId;
  /** The adapter that now supersedes this path. */
  supersededBy: AgentAdapterId;
  /** Human-readable suggestion. */
  suggestion: string;
}

const LEGACY_PATH_DEFS: LegacyPathDef[] = [
  {
    oldPath: ".agents/rules/{projectName}-best-practices.md",
    oldAgent: "codex",
    supersededBy: "codex",
    suggestion:
      "Codex skills now live at .agents/skills/{projectName}-codex-best-practices/SKILL.md. " +
      "Delete this file after confirming the new file exists.",
  },
  {
    oldPath: ".antigravity/rules/{projectName}-best-practices.md",
    oldAgent: "antigravity",
    supersededBy: "antigravity",
    suggestion:
      "Antigravity skills now live at .agents/skills/{projectName}-antigravity-best-practices/SKILL.md. " +
      "Delete this file after confirming the new file exists.",
  },
];

/**
 * Detect legacy generated files from pre-v1.0.17 adapter paths.
 * Only flags files that contain the @mp-sentinel-generated metadata marker.
 * User-authored files without metadata are ignored.
 */
export async function detectLegacyGeneratedFiles(
  projectRoot: string,
  projectName: string,
): Promise<LegacyFileInfo[]> {
  const results: LegacyFileInfo[] = [];

  for (const def of LEGACY_PATH_DEFS) {
    const relPath = def.oldPath.replace(/\{projectName\}/g, projectName);
    const absPath = join(projectRoot, relPath);

    if (!existsSync(absPath)) continue;

    let content: string;
    try {
      content = await readFile(absPath, "utf-8");
    } catch {
      continue;
    }

    const meta = parseMetadataFromContent(content);
    if (!meta) continue; // User-authored file, skip
    if (meta.agent !== def.oldAgent) continue; // Generated by a different adapter, skip

    results.push({
      path: relPath,
      agent: def.oldAgent,
      supersededBy: def.supersededBy,
      suggestion: def.suggestion.replace(/\{projectName\}/g, projectName),
    });
  }

  return results;
}
