import { existsSync } from "node:fs";
import { readFile } from "node:fs/promises";
import { join, relative, sep, posix } from "node:path";
import fg from "fast-glob";
import type { AgentAdapterId, LegacyFileInfo } from "../../types/index.js";
import { METADATA_MARKER, parseMetadataFromContent } from "./metadata.js";

interface LegacyPathDef {
  /** The old path pattern. Use {projectName} placeholder. */
  oldPath: string;
  /** The adapter id that created this file. */
  oldAgent: AgentAdapterId;
  /** The adapter that now supersedes this path. */
  supersededBy: AgentAdapterId;
  /** Human-readable suggestion. */
  suggestion: string;
}

const LEGACY_PATH_DEFS: LegacyPathDef[] = [
  {
    oldPath: ".agents/rules/{projectName}-best-practices.md",
    oldAgent: "codex",
    supersededBy: "codex",
    suggestion:
      "Codex skills now live at .agents/skills/{projectName}-codex-best-practices/SKILL.md. " +
      "Delete this file after confirming the new file exists.",
  },
  {
    oldPath: ".antigravity/rules/{projectName}-best-practices.md",
    oldAgent: "antigravity",
    supersededBy: "antigravity",
    suggestion:
      "Antigravity skills now live at .agents/skills/{projectName}-antigravity-best-practices/SKILL.md. " +
      "Delete this file after confirming the new file exists.",
  },
  {
    oldPath: ".windsurf/rules/{projectName}-best-practices.md",
    oldAgent: "windsurf",
    supersededBy: "windsurf",
    suggestion:
      "Windsurf skills now live at .windsurf/skills/{projectName}-windsurf-best-practices/SKILL.md. " +
      "Delete this file after confirming the new file exists.",
  },
  {
    oldPath: ".roo/rules/{projectName}-best-practices.md",
    oldAgent: "roo",
    supersededBy: "roo",
    suggestion:
      "Roo Code skills now live at .roo/skills/{projectName}-roo-best-practices/SKILL.md. " +
      "Delete this file after confirming the new file exists.",
  },
  {
    oldPath: ".clinerules/{projectName}-best-practices.md",
    oldAgent: "cline",
    supersededBy: "cline",
    suggestion:
      "Cline skills now live at .cline/skills/{projectName}-cline-best-practices/SKILL.md. " +
      "Delete this file after confirming the new file exists.",
  },
];

/**
 * Current expected output path prefixes per agent.
 * Directory adapters (claude, codex, antigravity) use a directory prefix;
 * single-file adapters use the exact file path.
 */
type ExpectedPathFn = (projectName: string) => string[];

const CURRENT_OUTPUT_PREFIXES: Partial<Record<AgentAdapterId, ExpectedPathFn>> = {
  claude: (pn) => [`.claude/skills/${pn}-best-practices/`],
  cursor: (pn) => [`.cursor/rules/${pn}-best-practices.mdc`],
  codex: (pn) => [`.agents/skills/${pn}-codex-best-practices/`],
  windsurf: (pn) => [`.windsurf/skills/${pn}-windsurf-best-practices/`],
  antigravity: (pn) => [`.agents/skills/${pn}-antigravity-best-practices/`],
  cline: (pn) => [`.cline/skills/${pn}-cline-best-practices/`],
  generic: (pn) => [`.agents/rules/${pn}-best-practices.md`],
  // Phase 4.2 adapters
  aider: () => [`CONVENTIONS.md`],
  continue: (pn) => [`.continue/rules/${pn}-best-practices.md`],
  roo: (pn) => [`.roo/skills/${pn}-roo-best-practices/`],
  copilot: () => [`.github/copilot-instructions.md`],
  zed: (pn) => [`.agents/skills/${pn}-zed-best-practices/`],
  jetbrains: () => [`.junie/AGENTS.md`],
};

/** Root-level directories where agent adapters write output. */
const KNOWN_AGENT_DIRS = [
  ".claude",
  ".cline",
  ".clinerules",
  ".cursor",
  ".agents",
  ".windsurf",
  ".antigravity",
  ".roo",
];

/**
 * Normalize a path to forward-slash format for comparison.
 */
function toPosix(p: string): string {
  return p.split(sep).join(posix.sep);
}

/**
 * Detect legacy generated files from pre-v1.0.17 adapter paths.
 * Only flags files that contain the @mp-sentinel-generated metadata marker.
 * User-authored files without metadata are ignored.
 */
export async function detectLegacyGeneratedFiles(
  projectRoot: string,
  projectName: string,
): Promise<LegacyFileInfo[]> {
  const results: LegacyFileInfo[] = [];

  for (const def of LEGACY_PATH_DEFS) {
    const relPath = def.oldPath.replace(/\{projectName\}/g, projectName);
    const absPath = join(projectRoot, relPath);

    if (!existsSync(absPath)) continue;

    let content: string;
    try {
      content = await readFile(absPath, "utf-8");
    } catch {
      continue;
    }

    const meta = parseMetadataFromContent(content);
    if (!meta) continue; // User-authored file, skip
    if (meta.agent !== def.oldAgent) continue; // Generated by a different adapter, skip

    results.push({
      path: relPath,
      agent: def.oldAgent,
      supersededBy: def.supersededBy,
      suggestion: def.suggestion.replace(/\{projectName\}/g, projectName),
    });
  }

  return results;
}

/**
 * Detect generated files with @mp-sentinel-generated metadata under known agent
 * directories that are NOT at expected current output paths.
 *
 * This catches artifacts like a claude-style SKILL.md mistakenly placed under
 * `.clinerules/` — the file's metadata says agent=claude but its path isn't
 * the expected `.claude/skills/<project>-best-practices/` directory.
 *
 * Files without metadata are never flagged. Files at expected paths are never
 * flagged (even if they also match a legacy path, those are handled by
 * detectLegacyGeneratedFiles).
 */
export async function detectUnexpectedGeneratedFiles(
  projectRoot: string,
  projectName: string,
): Promise<LegacyFileInfo[]> {
  const results: LegacyFileInfo[] = [];

  // Resolve all expected path prefixes for the current project
  const expectedPrefixes = new Map<AgentAdapterId, string[]>();
  for (const [agent, fn] of Object.entries(CURRENT_OUTPUT_PREFIXES)) {
    if (fn) {
      expectedPrefixes.set(agent as AgentAdapterId, fn(projectName));
    }
  }

  // Scan each known agent directory for markdown files
  for (const dir of KNOWN_AGENT_DIRS) {
    const absDir = join(projectRoot, dir);
    if (!existsSync(absDir)) continue;

    let found: string[];
    try {
      found = await fg(["**/*.md", "**/*.mdc"], { cwd: absDir, absolute: true, onlyFiles: true });
    } catch {
      continue;
    }

    for (const absPath of found) {
      const relPath = toPosix(relative(projectRoot, absPath));

      // Skip files that are NOT under the known dir (safety check)
      if (!relPath.startsWith(dir + "/")) continue;

      let content: string;
      try {
        content = await readFile(absPath, "utf-8");
      } catch {
        continue;
      }

      // Must contain the metadata marker
      if (!content.includes(METADATA_MARKER)) continue;

      const meta = parseMetadataFromContent(content);
      if (!meta) continue;

      const fileAgent = meta.agent as AgentAdapterId;

      // Check if this file's path is expected for this agent
      const prefixes = expectedPrefixes.get(fileAgent);
      if (!prefixes || prefixes.length === 0) {
        // Unknown agent — advisory
        results.push({
          path: relPath,
          agent: fileAgent,
          supersededBy: fileAgent,
          suggestion:
            `Generated file for unknown agent "${fileAgent}" at unexpected path. ` +
            `Review and delete if no longer needed.`,
        });
        continue;
      }

      const isExpected = prefixes.some((prefix) => relPath.startsWith(prefix));
      if (isExpected) continue; // At expected path, not unexpected

      // Also skip if this file matches a known LEGACY_PATH_DEFS entry for the
      // SAME agent (handled by detectLegacyGeneratedFiles). A file at a legacy
      // path but generated by a different agent is still unexpected.
      const matchesLegacy = LEGACY_PATH_DEFS.some(
        (def) =>
          def.oldPath.replace(/\{projectName\}/g, projectName) === relPath &&
          def.oldAgent === fileAgent,
      );
      if (matchesLegacy) continue;

      // This file has mp-sentinel metadata but is at an unexpected path for its agent
      const expectedDesc = prefixes.map((p) => `"${p}"`).join(" or ");
      results.push({
        path: relPath,
        agent: fileAgent,
        supersededBy: fileAgent,
        suggestion:
          `Generated file for agent "${fileAgent}" found at unexpected path. ` +
          `Expected under ${expectedDesc}. ` +
          `Delete this file after confirming official output exists.`,
      });
    }
  }

  return results;
}

/**
 * Combined detection: legacy path matches + unexpected generated files under known dirs.
 * Deduplicates by path so the same file is not reported twice.
 */
export async function detectAllLegacyAndUnexpected(
  projectRoot: string,
  projectName: string,
): Promise<LegacyFileInfo[]> {
  const legacy = await detectLegacyGeneratedFiles(projectRoot, projectName);
  const unexpected = await detectUnexpectedGeneratedFiles(projectRoot, projectName);

  const seen = new Set(legacy.map((f) => f.path));
  const combined = [...legacy];

  for (const f of unexpected) {
    if (!seen.has(f.path)) {
      seen.add(f.path);
      combined.push(f);
    }
  }

  return combined;
}
