import { existsSync } from "node:fs";
import { join } from "node:path";
import type {
  AgentAdapter,
  AgentAdapterId,
  GeneratedSkillFile,
  SkillsGenerationContext,
  SourceIndex,
} from "../../../types/index.js";
import { generateContent } from "../content.js";

export const antigravityAdapter: AgentAdapter = {
  id: "antigravity" as AgentAdapterId,
  label: "Google Antigravity (.agents/skills/)",

  spec: {
    officialDocsUrl: "https://antigravity.google/docs/skills",
    outputKind: "skill",
    workspacePath: ".agents/skills/{projectName}-antigravity-best-practices/",
    requiredFiles: ["SKILL.md"],
    frontmatterRules: {
      required: ["description"],
      optional: ["name"],
    },
    sizeLimit: 20000,
  },

  detect(projectRoot: string): boolean {
    return existsSync(join(projectRoot, ".antigravity")) || existsSync(join(projectRoot, ".agent"));
  },

  getDefaultOutput(projectRoot: string, projectName: string): string {
    return join(projectRoot, ".agents", "skills", `${projectName}-antigravity-best-practices`);
  },

  async generate(
    index: SourceIndex | null,
    context: SkillsGenerationContext,
  ): Promise<GeneratedSkillFile[]> {
    const { projectName, enrichment, knowledgeBase } = context;
    const content = generateContent(index, projectName, enrichment, knowledgeBase);
    const skillDir = this.getDefaultOutput(context.projectRoot, projectName);

    const skillMd = [
      `---`,
      `name: ${content.projectName}-antigravity-best-practices`,
      `description: Best practices and architecture guide for ${content.projectName} (auto-generated by mp-sentinel)`,
      `---`,
      ``,
      `# ${content.projectName} Best Practices`,
      ``,
      `> Auto-generated by mp-sentinel - re-run \`mp-sentinel create-skills\` to update.`,
      ``,
      content.sections.agentWorkflow,
      ``,
      content.sections.referenceRouting,
      ``,
      content.sections.overview,
      ``,
      content.sections.languageRules,
      ``,
      content.sections.cleanCodePolicy,
      ``,
      content.sections.fileSizePolicy,
      ``,
      content.sections.architecture,
      ``,
      content.sections.hubFiles,
      ``,
      content.sections.modules,
      ``,
      content.sections.codebaseMap,
      ``,
      content.sections.testingMap,
      ``,
      content.sections.dependencies,
      ``,
      content.sections.publicApi,
      ``,
      content.sections.profileRules,
      content.sections.aiEnrichment,
      ``,
      `## References`,
      ``,
      `- [Code Style](./references/code-style.md)`,
      `- [Language Patterns](./references/language-patterns.md)`,
      `- [Clean Code Checklist](./references/clean-code-checklist.md)`,
    ]
      .filter((s) => s !== undefined && s !== null && s !== "")
      .join("\n");

    const files: GeneratedSkillFile[] = [
      { outputPath: join(skillDir, "SKILL.md"), content: skillMd },
      {
        outputPath: join(skillDir, "references", "code-style.md"),
        content: content.references.codeStyle || "# Code Style\n\nNo style data available.",
      },
      {
        outputPath: join(skillDir, "references", "language-patterns.md"),
        content:
          content.references.languagePatterns ||
          "# Language Patterns\n\nNo language data available.",
      },
      {
        outputPath: join(skillDir, "references", "clean-code-checklist.md"),
        content:
          content.references.cleanCodeChecklist ||
          "# Clean Code Checklist\n\nNo policy data available.",
      },
    ];

    return files;
  },
};
