import { existsSync } from "node:fs";
import { join } from "node:path";
import type {
  AgentAdapter,
  AgentAdapterId,
  GeneratedSkillFile,
  SkillsGenerationContext,
  SourceIndex,
} from "../../../types/index.js";
import { generateContent } from "../content.js";

export const antigravityAdapter: AgentAdapter = {
  id: "antigravity" as AgentAdapterId,
  label: "Google Antigravity (.antigravity/rules/)",

  detect(projectRoot: string): boolean {
    return existsSync(join(projectRoot, ".antigravity")) || existsSync(join(projectRoot, ".agent"));
  },

  getDefaultOutput(projectRoot: string, projectName: string): string {
    return join(projectRoot, ".antigravity", "rules", `${projectName}-best-practices.md`);
  },

  async generate(
    index: SourceIndex | null,
    context: SkillsGenerationContext,
  ): Promise<GeneratedSkillFile[]> {
    const { projectName, enrichment, knowledgeBase } = context;
    const content = generateContent(index, projectName, enrichment, knowledgeBase);
    const outputPath = this.getDefaultOutput(context.projectRoot, projectName);

    const body = [
      `# ${content.projectName} Best Practices`,
      ``,
      `> Auto-generated by mp-sentinel — re-run \`mp-sentinel create-skills\` to update.`,
      ``,
      content.sections.agentWorkflow,
      ``,
      content.sections.overview,
      ``,
      content.sections.architecture,
      ``,
      content.sections.hubFiles,
      ``,
      content.sections.modules,
      ``,
      content.sections.codebaseMap,
      ``,
      content.sections.testingMap,
      ``,
      content.sections.dependencies,
      ``,
      content.sections.publicApi,
      ``,
      content.sections.profileRules,
      content.sections.aiEnrichment,
    ]
      .filter((s) => s !== undefined && s !== null && s !== "")
      .join("\n");

    return [{ outputPath, content: body }];
  },
};
