import { existsSync } from "node:fs";
import { join } from "node:path";
import type {
  AgentAdapter,
  AgentAdapterId,
  GeneratedSkillFile,
  SkillsGenerationContext,
  SourceIndex,
} from "../../../types/index.js";
import { generateContent } from "../content.js";

export const claudeAdapter: AgentAdapter = {
  id: "claude" as AgentAdapterId,
  label: "Claude Code (.claude/skills/)",

  detect(projectRoot: string): boolean {
    return existsSync(join(projectRoot, ".claude"));
  },

  getDefaultOutput(projectRoot: string, projectName: string): string {
    return join(projectRoot, ".claude", "skills", `${projectName}-best-practices`);
  },

  async generate(
    index: SourceIndex | null,
    context: SkillsGenerationContext,
  ): Promise<GeneratedSkillFile[]> {
    const { projectName } = context;
    const content = generateContent(index, projectName);
    const skillDir = this.getDefaultOutput(context.projectRoot, projectName);

    const skillMd = [
      `---`,
      `name: ${content.projectName}-best-practices`,
      `description: Best practices and architecture guide for ${content.projectName} (auto-generated by mp-sentinel)`,
      `---`,
      ``,
      `# ${content.projectName} Best Practices`,
      ``,
      `> Auto-generated by mp-sentinel — re-run \`mp-sentinel create-skills\` to update.`,
      ``,
      content.sections.overview,
      ``,
      `## References`,
      ``,
      `- [Architecture & Hub Files](./references/architecture.md)`,
      `- [Module Map](./references/modules.md)`,
      `- [Profile Rules](./references/commands.md)`,
    ].join("\n");

    const architectureMd = [content.sections.architecture, content.sections.hubFiles]
      .filter(Boolean)
      .join("\n\n");

    const commandsMd = [content.sections.profileRules].filter(Boolean).join("\n\n");

    return [
      { outputPath: join(skillDir, "SKILL.md"), content: skillMd },
      {
        outputPath: join(skillDir, "references", "architecture.md"),
        content: architectureMd || "# Architecture\n\nNo graph data available.",
      },
      {
        outputPath: join(skillDir, "references", "modules.md"),
        content: content.sections.modules || "# Module Map\n\nNo index available.",
      },
      {
        outputPath: join(skillDir, "references", "commands.md"),
        content: commandsMd || "# Commands\n\nNo index available.",
      },
    ];
  },
};
