import { existsSync } from "node:fs";
import { join } from "node:path";
import type {
  AgentAdapter,
  AgentAdapterId,
  GeneratedSkillFile,
  SkillsGenerationContext,
  SourceIndex,
} from "../../../types/index.js";
import { generateContent } from "../content.js";

export const claudeAdapter: AgentAdapter = {
  id: "claude" as AgentAdapterId,
  label: "Claude Code (.claude/skills/)",

  spec: {
    officialDocsUrl: "https://docs.anthropic.com/en/docs/claude-code/skills",
    outputKind: "skill",
    workspacePath: ".claude/skills/{projectName}-best-practices/",
    requiredFiles: ["SKILL.md"],
    frontmatterRules: {
      required: ["description"],
      optional: ["name"],
    },
    sizeLimit: 0,
  },

  detect(projectRoot: string): boolean {
    return existsSync(join(projectRoot, ".claude"));
  },

  getDefaultOutput(projectRoot: string, projectName: string): string {
    return join(projectRoot, ".claude", "skills", `${projectName}-best-practices`);
  },

  async generate(
    index: SourceIndex | null,
    context: SkillsGenerationContext,
  ): Promise<GeneratedSkillFile[]> {
    const { projectName, enrichment, knowledgeBase } = context;
    const content = generateContent(index, projectName, enrichment, knowledgeBase);

    const skillDir = this.getDefaultOutput(context.projectRoot, projectName);

    const refs: string[] = [
      `- [Architecture & Hub Files](./references/architecture.md)`,
      `- [Module Map](./references/modules.md)`,
      `- [Profile Rules & Commands](./references/commands.md)`,
      `- [Codebase Map](./references/codebase-map.md)`,
      `- [Testing Map](./references/testing-map.md)`,
      `- [Dependencies](./references/dependencies.md)`,
      `- [Public API](./references/public-api.md)`,
      `- [Code Style](./references/code-style.md)`,
      `- [Language Patterns](./references/language-patterns.md)`,
      `- [Clean Code Checklist](./references/clean-code-checklist.md)`,
    ];

    const skillMd = [
      `---`,
      `name: ${content.projectName}-best-practices`,
      `description: Best practices and architecture guide for ${content.projectName} (auto-generated by mp-sentinel)`,
      `---`,
      ``,
      `# ${content.projectName} Best Practices`,
      ``,
      `> Auto-generated by mp-sentinel - re-run \`mp-sentinel create-skills\` to update.`,
      ``,
      content.sections.agentWorkflow,
      ``,
      content.sections.referenceRouting,
      ``,
      content.sections.overview,
      ``,
      content.sections.languageRules,
      ``,
      content.sections.cleanCodePolicy,
      ``,
      content.sections.fileSizePolicy,
      ``,
      `## References`,
      ``,
      ...refs,
    ].join("\n");

    const architectureMd = [content.sections.architecture, content.sections.hubFiles]
      .filter(Boolean)
      .join("\n\n");

    const commandsMd = [content.sections.profileRules].filter(Boolean).join("\n\n");

    const files: GeneratedSkillFile[] = [
      { outputPath: join(skillDir, "SKILL.md"), content: skillMd },
      {
        outputPath: join(skillDir, "references", "architecture.md"),
        content: architectureMd || "# Architecture\n\nNo graph data available.",
      },
      {
        outputPath: join(skillDir, "references", "modules.md"),
        content: content.sections.modules || "# Module Map\n\nNo index available.",
      },
      {
        outputPath: join(skillDir, "references", "commands.md"),
        content: commandsMd || "# Commands\n\nNo index available.",
      },
      {
        outputPath: join(skillDir, "references", "codebase-map.md"),
        content: content.sections.codebaseMap || "# Codebase Map\n\nNo index available.",
      },
      {
        outputPath: join(skillDir, "references", "testing-map.md"),
        content: content.sections.testingMap || "# Testing Map\n\nNo index available.",
      },
      {
        outputPath: join(skillDir, "references", "dependencies.md"),
        content: content.sections.dependencies || "# Dependencies\n\nNo index available.",
      },
      {
        outputPath: join(skillDir, "references", "public-api.md"),
        content: content.sections.publicApi || "# Public API\n\nNo index available.",
      },
      {
        outputPath: join(skillDir, "references", "code-style.md"),
        content: content.references.codeStyle || "# Code Style\n\nNo style data available.",
      },
      {
        outputPath: join(skillDir, "references", "language-patterns.md"),
        content:
          content.references.languagePatterns ||
          "# Language Patterns\n\nNo language data available.",
      },
      {
        outputPath: join(skillDir, "references", "clean-code-checklist.md"),
        content:
          content.references.cleanCodeChecklist ||
          "# Clean Code Checklist\n\nNo policy data available.",
      },
    ];

    return files;
  },
};
