import { existsSync } from "node:fs";
import { join } from "node:path";
import type {
  AgentAdapter,
  AgentAdapterId,
  GeneratedSkillFile,
  SkillsGenerationContext,
  SourceIndex,
} from "../../../types/index.js";
import { generateContent } from "../content.js";

export const codexAdapter: AgentAdapter = {
  id: "codex" as AgentAdapterId,
  label: "Codex / OpenAI (.agents/rules/)",

  detect(projectRoot: string): boolean {
    return (
      existsSync(join(projectRoot, ".codex")) ||
      existsSync(join(projectRoot, ".agents")) ||
      // Only treat a root AGENTS.md as a codex signal if .agents/ also exists,
      // so we don't collide with mp-sentinel's own AGENTS.md in the user's repo.
      (existsSync(join(projectRoot, "AGENTS.md")) && existsSync(join(projectRoot, ".agents")))
    );
  },

  getDefaultOutput(projectRoot: string, projectName: string): string {
    return join(projectRoot, ".agents", "rules", `${projectName}-best-practices.md`);
  },

  async generate(
    index: SourceIndex | null,
    context: SkillsGenerationContext,
  ): Promise<GeneratedSkillFile[]> {
    const { projectName, enrichment, knowledgeBase } = context;
    const content = generateContent(index, projectName, enrichment, knowledgeBase);
    const outputPath = this.getDefaultOutput(context.projectRoot, projectName);

    const body = [
      `# ${content.projectName} Best Practices`,
      ``,
      `> Auto-generated by mp-sentinel — re-run \`mp-sentinel create-skills\` to update.`,
      ``,
      content.sections.agentWorkflow,
      ``,
      content.sections.overview,
      ``,
      content.sections.architecture,
      ``,
      content.sections.hubFiles,
      ``,
      content.sections.modules,
      ``,
      content.sections.codebaseMap,
      ``,
      content.sections.testingMap,
      ``,
      content.sections.dependencies,
      ``,
      content.sections.publicApi,
      ``,
      content.sections.profileRules,
      content.sections.aiEnrichment,
    ]
      .filter((s) => s !== undefined && s !== null && s !== "")
      .join("\n");

    return [{ outputPath, content: body }];
  },
};
