/**
 * Continue.dev adapter (Phase 4.2).
 *
 * Continue is a VS Code / JetBrains IDE extension. It supports per-project
 * Markdown rules under `.continue/rules/` with YAML frontmatter
 * (`name`, `description`, `alwaysApply`) that Continue picks up as a
 * system rule -- that's where we write.
 *
 * Detection signals:
 *   - `.continue/` directory
 *   - existing `.continuerc.json`
 */

import { existsSync } from "node:fs";
import { join } from "node:path";
import type {
  AgentAdapter,
  AgentAdapterId,
  GeneratedSkillFile,
  SkillsGenerationContext,
  SourceIndex,
} from "../../../types/index.js";
import { renderConciseRules } from "./rule-renderer.js";

export const continueAdapter: AgentAdapter = {
  id: "continue" as AgentAdapterId,
  label: "Continue.dev (.continue/rules/)",

  spec: {
    officialDocsUrl: "https://docs.continue.dev/customize/deep-dives/rules",
    outputKind: "rule",
    workspacePath: ".continue/rules/{projectName}-best-practices.md",
    requiredFiles: [],
    frontmatterRules: { required: [] },
    sizeLimit: 20000,
  },

  detect(projectRoot: string): boolean {
    return (
      existsSync(join(projectRoot, ".continue")) ||
      existsSync(join(projectRoot, ".continuerc.json"))
    );
  },

  getDefaultOutput(projectRoot: string, projectName: string): string {
    return join(projectRoot, ".continue", "rules", `${projectName}-best-practices.md`);
  },

  async generate(
    index: SourceIndex | null,
    context: SkillsGenerationContext,
  ): Promise<GeneratedSkillFile[]> {
    const outputPath = this.getDefaultOutput(context.projectRoot, context.projectName);
    return renderConciseRules(index, context, outputPath, {
      titleTemplate: "{projectName} Best Practices",
      frontmatterLines: (projectName) => [
        `---`,
        `name: ${projectName}-best-practices`,
        `description: Best practices for ${projectName} (auto-generated by mp-sentinel)`,
        `alwaysApply: true`,
        `---`,
        ``,
      ],
    });
  },
};
