/**
 * Continue.dev adapter (Phase 4.2).
 *
 * Continue is a VS Code / JetBrains IDE extension. It supports per-project
 * `rules` configured in `.continue/config.json` (or `.continuerc.json`).
 * The simpler path the project documents for ad-hoc usage is to ship a
 * Markdown file under `.continue/rules/` that Continue picks up as a
 * system rule -- that's where we write.
 *
 * Detection signals:
 *   - `.continue/` directory
 *   - existing `.continuerc.json`
 */

import { existsSync } from "node:fs";
import { join } from "node:path";
import type {
  AgentAdapter,
  AgentAdapterId,
  GeneratedSkillFile,
  SkillsGenerationContext,
  SourceIndex,
} from "../../../types/index.js";
import { generateContent } from "../content.js";

export const continueAdapter: AgentAdapter = {
  id: "continue" as AgentAdapterId,
  label: "Continue.dev (.continue/rules/)",

  spec: {
    officialDocsUrl: "https://docs.continue.dev/customize/deep-dives/rules",
    outputKind: "rule",
    workspacePath: ".continue/rules/{projectName}-best-practices.md",
    requiredFiles: [],
    frontmatterRules: { required: [] },
    sizeLimit: 20000,
  },

  detect(projectRoot: string): boolean {
    return (
      existsSync(join(projectRoot, ".continue")) ||
      existsSync(join(projectRoot, ".continuerc.json"))
    );
  },

  getDefaultOutput(projectRoot: string, projectName: string): string {
    return join(projectRoot, ".continue", "rules", `${projectName}-best-practices.md`);
  },

  async generate(
    index: SourceIndex | null,
    context: SkillsGenerationContext,
  ): Promise<GeneratedSkillFile[]> {
    const { projectName, enrichment, knowledgeBase } = context;
    const content = generateContent(
      index,
      projectName,
      enrichment,
      knowledgeBase,
      context.codeStyleProfile,
      context.policies,
      context.disableRules,
    );
    const outputPath = this.getDefaultOutput(context.projectRoot, projectName);

    const body = [
      `# ${content.projectName} Best Practices`,
      ``,
      `> Auto-generated by mp-sentinel - re-run \`npx mp-sentinel create-skills\` to update.`,
      ``,
      content.sections.agentWorkflow,
      ``,
      content.sections.referenceRouting,
      ``,
      content.sections.overview,
      ``,
      content.sections.languageRules,
      ``,
      content.sections.cleanCodePolicy,
      ``,
      content.sections.fileSizePolicy,
      ``,
      content.sections.architecture,
      ``,
      content.sections.hubFiles,
      ``,
      content.sections.modules,
      ``,
      content.sections.codebaseMap,
      ``,
      content.sections.testingMap,
      ``,
      content.sections.dependencies,
      ``,
      content.sections.publicApi,
      ``,
      content.sections.profileRules,
      content.sections.aiEnrichment,
    ]
      .filter((s) => s !== undefined && s !== null && s !== "")
      .join("\n");

    return [{ outputPath, content: body }];
  },
};
