/**
 * GitHub Copilot (Workspace + custom instructions) adapter (Phase 4.2).
 *
 * GitHub's "Adding repository custom instructions for GitHub Copilot"
 * documents `.github/copilot-instructions.md` as the canonical path that
 * Copilot reads for project-wide rules. This adapter ships there.
 *
 * Detection signals:
 *   - `.github/copilot-instructions.md` already exists
 *   - `.github/` directory exists (best-effort signal that the project
 *     uses GitHub tooling)
 */

import { existsSync } from "node:fs";
import { join } from "node:path";
import type {
  AgentAdapter,
  AgentAdapterId,
  GeneratedSkillFile,
  SkillsGenerationContext,
  SourceIndex,
} from "../../../types/index.js";
import { generateContent } from "../content.js";

export const copilotAdapter: AgentAdapter = {
  id: "copilot" as AgentAdapterId,
  label: "GitHub Copilot (.github/copilot-instructions.md)",

  spec: {
    officialDocsUrl: "https://docs.github.com/en/copilot/concepts/prompting/response-customization",
    outputKind: "rule",
    workspacePath: ".github/copilot-instructions.md",
    requiredFiles: [],
    frontmatterRules: { required: [] },
    sizeLimit: 20000,
  },

  detect(projectRoot: string): boolean {
    return (
      existsSync(join(projectRoot, ".github", "copilot-instructions.md")) ||
      existsSync(join(projectRoot, ".github"))
    );
  },

  getDefaultOutput(projectRoot: string, _projectName: string): string {
    return join(projectRoot, ".github", "copilot-instructions.md");
  },

  async generate(
    index: SourceIndex | null,
    context: SkillsGenerationContext,
  ): Promise<GeneratedSkillFile[]> {
    const { projectName, enrichment, knowledgeBase } = context;
    const content = generateContent(
      index,
      projectName,
      enrichment,
      knowledgeBase,
      context.codeStyleProfile,
      context.policies,
      context.disableRules,
    );
    const outputPath = this.getDefaultOutput(context.projectRoot, projectName);

    // Copilot recommends short, single-purpose instructions (~few KB).
    // We still emit the structured body - the size limit in spec acts
    // as a guardrail in the quality gate.
    const body = [
      `# ${content.projectName} Copilot Instructions`,
      ``,
      `Auto-generated by mp-sentinel - re-run \`npx mp-sentinel create-skills\` to update.`,
      ``,
      content.sections.agentWorkflow,
      ``,
      content.sections.referenceRouting,
      ``,
      content.sections.overview,
      ``,
      content.sections.languageRules,
      ``,
      content.sections.cleanCodePolicy,
      ``,
      content.sections.fileSizePolicy,
      ``,
      content.sections.architecture,
      ``,
      content.sections.hubFiles,
      ``,
      content.sections.modules,
      ``,
      content.sections.codebaseMap,
      ``,
      content.sections.testingMap,
      ``,
      content.sections.dependencies,
      ``,
      content.sections.publicApi,
      ``,
      content.sections.profileRules,
      content.sections.aiEnrichment,
    ]
      .filter((s) => s !== undefined && s !== null && s !== "")
      .join("\n");

    return [{ outputPath, content: body }];
  },
};
