import { existsSync } from "node:fs";
import { join } from "node:path";
import type {
  AgentAdapter,
  AgentAdapterId,
  GeneratedSkillFile,
  SkillsGenerationContext,
  SourceIndex,
} from "../../../types/index.js";
import { renderConciseRules } from "./rule-renderer.js";

export const cursorAdapter: AgentAdapter = {
  id: "cursor" as AgentAdapterId,
  label: "Cursor (.cursor/rules/)",

  spec: {
    officialDocsUrl: "https://docs.cursor.com/context/rules-for-ai",
    outputKind: "rule",
    workspacePath: ".cursor/rules/{projectName}-best-practices.mdc",
    requiredFiles: [],
    frontmatterRules: {
      required: ["description"],
    },
    sizeLimit: 20000,
  },

  detect(projectRoot: string): boolean {
    return existsSync(join(projectRoot, ".cursor"));
  },

  getDefaultOutput(projectRoot: string, projectName: string): string {
    return join(projectRoot, ".cursor", "rules", `${projectName}-best-practices.mdc`);
  },

  async generate(
    index: SourceIndex | null,
    context: SkillsGenerationContext,
  ): Promise<GeneratedSkillFile[]> {
    const outputPath = this.getDefaultOutput(context.projectRoot, context.projectName);
    return renderConciseRules(index, context, outputPath, {
      titleTemplate: "{projectName} Best Practices",
      frontmatterLines: (projectName) => [
        `---`,
        `description: Best practices for ${projectName} (auto-generated by mp-sentinel)`,
        `globs: ["**/*.ts", "**/*.tsx", "**/*.js", "**/*.jsx"]`,
        `alwaysApply: false`,
        `---`,
        ``,
      ],
    });
  },
};
