import { existsSync } from "node:fs";
import { join } from "node:path";
import type {
  AgentAdapter,
  AgentAdapterId,
  GeneratedSkillFile,
  SkillsGenerationContext,
  SourceIndex,
} from "../../../types/index.js";
import { generateContent } from "../content.js";

export const cursorAdapter: AgentAdapter = {
  id: "cursor" as AgentAdapterId,
  label: "Cursor (.cursor/rules/)",

  spec: {
    officialDocsUrl: "https://docs.cursor.com/context/rules-for-ai",
    outputKind: "rule",
    workspacePath: ".cursor/rules/{projectName}-best-practices.mdc",
    requiredFiles: [],
    frontmatterRules: {
      required: ["description"],
    },
    sizeLimit: 20000,
  },

  detect(projectRoot: string): boolean {
    return existsSync(join(projectRoot, ".cursor"));
  },

  getDefaultOutput(projectRoot: string, projectName: string): string {
    return join(projectRoot, ".cursor", "rules", `${projectName}-best-practices.mdc`);
  },

  async generate(
    index: SourceIndex | null,
    context: SkillsGenerationContext,
  ): Promise<GeneratedSkillFile[]> {
    const { projectName, enrichment, knowledgeBase } = context;
    const content = generateContent(index, projectName, enrichment, knowledgeBase);
    const outputPath = this.getDefaultOutput(context.projectRoot, projectName);

    const body = [
      `---`,
      `description: Best practices for ${content.projectName} (auto-generated by mp-sentinel)`,
      `globs: ["**/*.ts", "**/*.tsx", "**/*.js", "**/*.jsx"]`,
      `alwaysApply: false`,
      `---`,
      ``,
      `# ${content.projectName} Best Practices`,
      ``,
      `> Auto-generated by mp-sentinel — re-run \`mp-sentinel create-skills\` to update.`,
      ``,
      content.sections.agentWorkflow,
      ``,
      content.sections.overview,
      ``,
      content.sections.architecture,
      ``,
      content.sections.hubFiles,
      ``,
      content.sections.modules,
      ``,
      content.sections.codebaseMap,
      ``,
      content.sections.testingMap,
      ``,
      content.sections.dependencies,
      ``,
      content.sections.publicApi,
      ``,
      content.sections.profileRules,
      content.sections.aiEnrichment,
    ]
      .filter((s) => s !== undefined && s !== null && s !== "")
      .join("\n");

    return [{ outputPath, content: body }];
  },
};
