import { existsSync } from "node:fs";
import { join } from "node:path";
import type {
  AgentAdapter,
  AgentAdapterId,
  GeneratedSkillFile,
  SkillsGenerationContext,
  SourceIndex,
} from "../../../types/index.js";
import { generateContent } from "../content.js";

export const cursorAdapter: AgentAdapter = {
  id: "cursor" as AgentAdapterId,
  label: "Cursor (.cursor/rules/)",

  detect(projectRoot: string): boolean {
    return existsSync(join(projectRoot, ".cursor"));
  },

  getDefaultOutput(projectRoot: string, projectName: string): string {
    return join(projectRoot, ".cursor", "rules", `${projectName}-best-practices.mdc`);
  },

  async generate(
    index: SourceIndex | null,
    context: SkillsGenerationContext,
  ): Promise<GeneratedSkillFile[]> {
    const { projectName } = context;
    const content = generateContent(index, projectName);
    const outputPath = this.getDefaultOutput(context.projectRoot, projectName);

    const body = [
      `---`,
      `description: Best practices for ${content.projectName} (auto-generated by mp-sentinel)`,
      `globs: ["**/*.ts", "**/*.tsx", "**/*.js", "**/*.jsx"]`,
      `alwaysApply: false`,
      `---`,
      ``,
      `# ${content.projectName} Best Practices`,
      ``,
      content.sections.overview,
      ``,
      content.sections.architecture,
      ``,
      content.sections.hubFiles,
      ``,
      content.sections.modules,
      ``,
      content.sections.commands,
      ``,
      content.sections.conventions,
    ]
      .filter((s) => s !== undefined)
      .join("\n");

    return [{ outputPath, content: body }];
  },
};
