import { join } from "node:path";
import type {
  AgentAdapter,
  AgentAdapterId,
  GeneratedSkillFile,
  SkillsGenerationContext,
  SourceIndex,
} from "../../../types/index.js";
import { generateContent } from "../content.js";

export const genericAdapter: AgentAdapter = {
  id: "generic" as AgentAdapterId,
  label: "Generic (.agents/rules/)",

  // Generic is a fallback — never auto-detected; only added explicitly
  detect(_projectRoot: string): boolean {
    return false;
  },

  getDefaultOutput(projectRoot: string, projectName: string): string {
    return join(projectRoot, ".agents", "rules", `${projectName}-best-practices.md`);
  },

  async generate(
    index: SourceIndex | null,
    context: SkillsGenerationContext,
  ): Promise<GeneratedSkillFile[]> {
    const { projectName } = context;
    const content = generateContent(index, projectName);
    const outputPath = this.getDefaultOutput(context.projectRoot, projectName);

    const body = [
      `# ${content.projectName} Best Practices`,
      ``,
      `> Auto-generated by mp-sentinel — re-run \`mp-sentinel create-skills\` to update.`,
      ``,
      content.sections.overview,
      ``,
      content.sections.architecture,
      ``,
      content.sections.hubFiles,
      ``,
      content.sections.modules,
      ``,
      content.sections.commands,
      ``,
      content.sections.conventions,
    ]
      .filter((s) => s !== undefined)
      .join("\n");

    return [{ outputPath, content: body }];
  },
};
