/**
 * JetBrains AI Assistant adapter (Phase 4.2).
 *
 * Junie (JetBrains' AI agent) reads project-scoped instructions from
 * `.junie/AGENTS.md` -- current Junie docs list `.junie/AGENTS.md` first
 * and call `.junie/guidelines.md` the legacy path, so we write the
 * current one.
 *
 * Detection signals:
 *   - `.junie/` directory
 *   - `.idea/` (IntelliJ-family IDE project marker)
 */

import { existsSync } from "node:fs";
import { join } from "node:path";
import type {
  AgentAdapter,
  AgentAdapterId,
  GeneratedSkillFile,
  SkillsGenerationContext,
  SourceIndex,
} from "../../../types/index.js";
import { generateContent } from "../content.js";

export const jetbrainsAdapter: AgentAdapter = {
  id: "jetbrains" as AgentAdapterId,
  label: "JetBrains AI / Junie (.junie/AGENTS.md)",

  spec: {
    officialDocsUrl: "https://www.jetbrains.com/help/junie/customize-guidelines.html",
    outputKind: "rule",
    workspacePath: ".junie/AGENTS.md",
    requiredFiles: [],
    frontmatterRules: { required: [] },
    sizeLimit: 20000,
  },

  detect(projectRoot: string): boolean {
    return existsSync(join(projectRoot, ".junie")) || existsSync(join(projectRoot, ".idea"));
  },

  getDefaultOutput(projectRoot: string, _projectName: string): string {
    return join(projectRoot, ".junie", "AGENTS.md");
  },

  async generate(
    index: SourceIndex | null,
    context: SkillsGenerationContext,
  ): Promise<GeneratedSkillFile[]> {
    const { projectName, enrichment, knowledgeBase } = context;
    const content = generateContent(
      index,
      projectName,
      enrichment,
      knowledgeBase,
      context.codeStyleProfile,
      context.policies,
      context.disableRules,
    );
    const outputPath = this.getDefaultOutput(context.projectRoot, projectName);

    const body = [
      `# ${content.projectName} Junie Guidelines`,
      ``,
      `Auto-generated by mp-sentinel - re-run \`npx mp-sentinel create-skills\` to update.`,
      ``,
      content.sections.agentWorkflow,
      ``,
      content.sections.referenceRouting,
      ``,
      content.sections.overview,
      ``,
      content.sections.languageRules,
      ``,
      content.sections.cleanCodePolicy,
      ``,
      content.sections.fileSizePolicy,
      ``,
      content.sections.architecture,
      ``,
      content.sections.hubFiles,
      ``,
      content.sections.modules,
      ``,
      content.sections.codebaseMap,
      ``,
      content.sections.testingMap,
      ``,
      content.sections.dependencies,
      ``,
      content.sections.publicApi,
      ``,
      content.sections.profileRules,
      content.sections.aiEnrichment,
    ]
      .filter((s) => s !== undefined && s !== null && s !== "")
      .join("\n");

    return [{ outputPath, content: body }];
  },
};
