/**
 * Roo Code adapter (Phase 4.2).
 *
 * Roo Code (a Cline fork) uses `.roo/rules/` (workspace) or
 * `.roo/rules-{mode}/` (workspace-mode-specific) for project-scoped
 * rules. We write to the workspace-level `.roo/rules/` so the file
 * applies regardless of mode.
 *
 * Detection signals:
 *   - `.roo/` directory
 *   - `.roorules` legacy file
 */

import { existsSync } from "node:fs";
import { join } from "node:path";
import type {
  AgentAdapter,
  AgentAdapterId,
  GeneratedSkillFile,
  SkillsGenerationContext,
  SourceIndex,
} from "../../../types/index.js";
import { generateContent } from "../content.js";

export const rooAdapter: AgentAdapter = {
  id: "roo" as AgentAdapterId,
  label: "Roo Code (.roo/rules/)",

  spec: {
    officialDocsUrl: "https://docs.roocode.com/features/custom-instructions",
    outputKind: "rule",
    workspacePath: ".roo/rules/{projectName}-best-practices.md",
    requiredFiles: [],
    frontmatterRules: { required: [] },
    sizeLimit: 20000,
  },

  detect(projectRoot: string): boolean {
    return existsSync(join(projectRoot, ".roo")) || existsSync(join(projectRoot, ".roorules"));
  },

  getDefaultOutput(projectRoot: string, projectName: string): string {
    return join(projectRoot, ".roo", "rules", `${projectName}-best-practices.md`);
  },

  async generate(
    index: SourceIndex | null,
    context: SkillsGenerationContext,
  ): Promise<GeneratedSkillFile[]> {
    const { projectName, enrichment, knowledgeBase } = context;
    const content = generateContent(
      index,
      projectName,
      enrichment,
      knowledgeBase,
      context.codeStyleProfile,
      context.policies,
      context.disableRules,
    );
    const outputPath = this.getDefaultOutput(context.projectRoot, projectName);

    const body = [
      `# ${content.projectName} Best Practices`,
      ``,
      `> Auto-generated by mp-sentinel - re-run \`npx mp-sentinel create-skills\` to update.`,
      ``,
      content.sections.agentWorkflow,
      ``,
      content.sections.referenceRouting,
      ``,
      content.sections.overview,
      ``,
      content.sections.languageRules,
      ``,
      content.sections.cleanCodePolicy,
      ``,
      content.sections.fileSizePolicy,
      ``,
      content.sections.architecture,
      ``,
      content.sections.hubFiles,
      ``,
      content.sections.modules,
      ``,
      content.sections.codebaseMap,
      ``,
      content.sections.testingMap,
      ``,
      content.sections.dependencies,
      ``,
      content.sections.publicApi,
      ``,
      content.sections.profileRules,
      content.sections.aiEnrichment,
    ]
      .filter((s) => s !== undefined && s !== null && s !== "")
      .join("\n");

    return [{ outputPath, content: body }];
  },
};
