/**
 * Shared concise rule renderer for single-file (rule-only) adapters:
 * Cursor, Continue, Copilot, Aider, JetBrains/Junie, and the generic
 * fallback.
 *
 * Rule files load eagerly into the agent's context, so unlike skill
 * folders they must stay concise: workflow contract, overview, language
 * and framework rules, code policies, and profile pitfalls. The bulky
 * maps (codebase, testing, dependencies, public API) are skill-folder
 * material and are intentionally omitted, as is the reference-routing
 * table (rule outputs ship no references/ directory).
 */

import type {
  GeneratedSkillFile,
  SkillsGenerationContext,
  SourceIndex,
} from "../../../types/index.js";
import { generateContent } from "../content.js";
import { renderRegenerateCommand } from "../package-manager.js";

export interface RuleRenderOptions {
  /** H1 title, e.g. "my-project Best Practices". `{projectName}` is substituted. */
  titleTemplate: string;
  /** Extra frontmatter lines including the `---` fences (e.g. Cursor .mdc). */
  frontmatterLines?: (projectName: string) => string[];
  /** Render the auto-generated note as a blockquote (default true). */
  blockquoteNote?: boolean;
}

/** Render a concise, agent-native single rule file. */
export function renderConciseRules(
  index: SourceIndex | null,
  context: SkillsGenerationContext,
  outputPath: string,
  options: RuleRenderOptions,
): GeneratedSkillFile[] {
  const { projectName, enrichment, knowledgeBase } = context;
  const content = generateContent(
    index,
    projectName,
    enrichment,
    knowledgeBase,
    context.codeStyleProfile,
    context.policies,
    context.disableRules,
  );

  const title = options.titleTemplate.replace(/\{projectName\}/g, content.projectName);
  const regen = renderRegenerateCommand(knowledgeBase?.packageManager, index?.project.scripts);
  const note = `Auto-generated by mp-sentinel - re-run \`${regen}\` to update.`;
  const noteLine = options.blockquoteNote === false ? note : `> ${note}`;

  const parts: Array<string | null> = [
    ...(options.frontmatterLines ? options.frontmatterLines(content.projectName) : []),
    `# ${title}`,
    ``,
    noteLine,
    ``,
    content.sections.agentWorkflowCompact,
    ...(content.sections.projectRules ? [``, content.sections.projectRules] : []),
    ``,
    content.sections.overview,
    ...(content.sections.detectedConventions ? [``, content.sections.detectedConventions] : []),
    ``,
    content.sections.languageRules,
    ``,
    content.sections.cleanCodePolicy,
    ``,
    content.sections.fileSizePolicy,
    ``,
    content.sections.profileRules,
    content.sections.aiEnrichment ? `` : null,
    content.sections.aiEnrichment,
  ];

  const body = parts.filter((s): s is string => s !== undefined && s !== null).join("\n");

  return [{ outputPath, content: body }];
}
