/**
 * Shared progressive-disclosure skill renderer.
 *
 * Every skill-capable agent (Claude, Codex, Antigravity, Zed, Windsurf,
 * Roo, Cline) gets the same layout: a lean SKILL.md that carries the
 * agent workflow, reference routing, overview, and policies — plus the
 * full reference set as separate files the agent loads on demand:
 *
 *   architecture, modules, commands, codebase-map, testing-map,
 *   dependencies, public-api, code-style, language-patterns,
 *   clean-code-checklist
 *
 * Adapters differ only in output directory and skill name. The
 * frontmatter `name` always matches the skill folder name (enforced by
 * the quality gate).
 */

import { join } from "node:path";
import type {
  GeneratedSkillFile,
  SkillsGenerationContext,
  SourceIndex,
} from "../../../types/index.js";
import { generateContent } from "../content.js";

/** Reference files every progressive skill ships (relative to skill dir). */
export const SKILL_REFERENCE_FILES: readonly string[] = [
  "references/architecture.md",
  "references/modules.md",
  "references/commands.md",
  "references/codebase-map.md",
  "references/testing-map.md",
  "references/dependencies.md",
  "references/public-api.md",
  "references/code-style.md",
  "references/language-patterns.md",
  "references/clean-code-checklist.md",
];

const REFERENCE_LINKS: readonly string[] = [
  `- [Architecture & Hub Files](./references/architecture.md)`,
  `- [Module Map](./references/modules.md)`,
  `- [Profile Rules & Commands](./references/commands.md)`,
  `- [Codebase Map](./references/codebase-map.md)`,
  `- [Testing Map](./references/testing-map.md)`,
  `- [Dependencies](./references/dependencies.md)`,
  `- [Public API](./references/public-api.md)`,
  `- [Code Style](./references/code-style.md)`,
  `- [Language Patterns](./references/language-patterns.md)`,
  `- [Clean Code Checklist](./references/clean-code-checklist.md)`,
];

/**
 * Render the lean SKILL.md + full reference set for a skill directory.
 *
 * @param skillDir   Absolute output directory for the skill.
 * @param skillName  Skill folder name (also the frontmatter `name`).
 */
export function renderProgressiveSkill(
  index: SourceIndex | null,
  context: SkillsGenerationContext,
  skillDir: string,
  skillName: string,
): GeneratedSkillFile[] {
  const { projectName, enrichment, knowledgeBase } = context;
  const content = generateContent(
    index,
    projectName,
    enrichment,
    knowledgeBase,
    context.codeStyleProfile,
    context.policies,
    context.disableRules,
  );

  const skillMdParts: string[] = [
    `---`,
    `name: ${skillName}`,
    `description: Best practices and architecture guide for ${content.projectName} (auto-generated by mp-sentinel)`,
    `---`,
    ``,
    `# ${content.projectName} Best Practices`,
    ``,
    `> Auto-generated by mp-sentinel - re-run \`npx mp-sentinel create-skills\` to update.`,
    ``,
    content.sections.agentWorkflow,
    ``,
    content.sections.referenceRouting,
    ``,
    content.sections.overview,
    ``,
    content.sections.languageRules,
    ``,
    content.sections.cleanCodePolicy,
    ``,
    content.sections.fileSizePolicy,
  ];
  if (content.sections.aiEnrichment) {
    skillMdParts.push(``, content.sections.aiEnrichment);
  }
  skillMdParts.push(``, `## References`, ``, ...REFERENCE_LINKS);
  const skillMd = skillMdParts.join("\n");

  const architectureMd = [content.sections.architecture, content.sections.hubFiles]
    .filter(Boolean)
    .join("\n\n");

  const commandsMd = [content.sections.profileRules].filter(Boolean).join("\n\n");

  return [
    { outputPath: join(skillDir, "SKILL.md"), content: skillMd },
    {
      outputPath: join(skillDir, "references", "architecture.md"),
      content: architectureMd || "# Architecture\n\nNo graph data available.",
    },
    {
      outputPath: join(skillDir, "references", "modules.md"),
      content: content.sections.modules || "# Module Map\n\nNo index available.",
    },
    {
      outputPath: join(skillDir, "references", "commands.md"),
      content: commandsMd || "# Commands\n\nNo index available.",
    },
    {
      outputPath: join(skillDir, "references", "codebase-map.md"),
      content: content.sections.codebaseMap || "# Codebase Map\n\nNo index available.",
    },
    {
      outputPath: join(skillDir, "references", "testing-map.md"),
      content: content.sections.testingMap || "# Testing Map\n\nNo index available.",
    },
    {
      outputPath: join(skillDir, "references", "dependencies.md"),
      content: content.sections.dependencies || "# Dependencies\n\nNo index available.",
    },
    {
      outputPath: join(skillDir, "references", "public-api.md"),
      content: content.sections.publicApi || "# Public API\n\nNo index available.",
    },
    {
      outputPath: join(skillDir, "references", "code-style.md"),
      content: content.references.codeStyle || "# Code Style\n\nNo style data available.",
    },
    {
      outputPath: join(skillDir, "references", "language-patterns.md"),
      content:
        content.references.languagePatterns || "# Language Patterns\n\nNo language data available.",
    },
    {
      outputPath: join(skillDir, "references", "clean-code-checklist.md"),
      content:
        content.references.cleanCodeChecklist ||
        "# Clean Code Checklist\n\nNo policy data available.",
    },
  ];
}
