import { existsSync } from "node:fs";
import { join } from "node:path";
import type {
  AgentAdapter,
  AgentAdapterId,
  GeneratedSkillFile,
  SkillsGenerationContext,
  SourceIndex,
} from "../../../types/index.js";
import { generateContent } from "../content.js";

export const windsurfAdapter: AgentAdapter = {
  id: "windsurf" as AgentAdapterId,
  label: "Windsurf (.windsurf/rules/)",

  spec: {
    officialDocsUrl: "https://docs.windsurf.com/rules",
    outputKind: "rule",
    workspacePath: ".windsurf/rules/{projectName}-best-practices.md",
    requiredFiles: [],
    frontmatterRules: {
      required: [],
    },
    sizeLimit: 20000,
  },

  detect(projectRoot: string): boolean {
    return existsSync(join(projectRoot, ".windsurf"));
  },

  getDefaultOutput(projectRoot: string, projectName: string): string {
    return join(projectRoot, ".windsurf", "rules", `${projectName}-best-practices.md`);
  },

  async generate(
    index: SourceIndex | null,
    context: SkillsGenerationContext,
  ): Promise<GeneratedSkillFile[]> {
    const { projectName, enrichment, knowledgeBase } = context;
    const content = generateContent(index, projectName, enrichment, knowledgeBase);
    const outputPath = this.getDefaultOutput(context.projectRoot, projectName);

    const body = [
      `# ${content.projectName} Best Practices`,
      ``,
      `> Auto-generated by mp-sentinel - re-run \`mp-sentinel create-skills\` to update.`,
      ``,
      content.sections.agentWorkflow,
      ``,
      content.sections.referenceRouting,
      ``,
      content.sections.overview,
      ``,
      content.sections.languageRules,
      ``,
      content.sections.cleanCodePolicy,
      ``,
      content.sections.fileSizePolicy,
      ``,
      content.sections.architecture,
      ``,
      content.sections.hubFiles,
      ``,
      content.sections.modules,
      ``,
      content.sections.codebaseMap,
      ``,
      content.sections.testingMap,
      ``,
      content.sections.dependencies,
      ``,
      content.sections.publicApi,
      ``,
      content.sections.profileRules,
      content.sections.aiEnrichment,
    ]
      .filter((s) => s !== undefined && s !== null && s !== "")
      .join("\n");

    return [{ outputPath, content: body }];
  },
};
